### ISSUE TITLE
"ReferenceError: self is not defined" error occurring in unstable branch

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js-cose-bilkent#117]
I created a minimal project that just performs the related commonjs requires (https://github.com/metincansiper/cose-bilkent-test) to reproduce this error . In this line (https://github.com/metincansiper/cose-bilkent-test/blob/main/package.json#L13) I am switching the cose-bilkent branch that is used (after refreshing the node_modules). When I am using the unstable branch of cose-bilkent I am seeing the following error:

```
/Users/siperm/Documents/Workspace/cose-bilkent-test/node_modules/cytoscape-cose-bilkent/cytoscape-cose-bilkent.js:10
})(self, function(__WEBPACK_EXTERNAL_MODULE__281__) {
   ^

ReferenceError: self is not defined
    at Object.<anonymous> (/Users/siperm/Documents/Workspace/cose-bilkent-test/node_modules/cytoscape-cose-bilkent/cytoscape-cose-bilkent.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/siperm/Documents/Workspace/cose-bilkent-test/index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
```

It works fine with the master branch of cose-bilkent.

**Comment by hasanbalci** [comment]
@metincansiper Can you please verify that this problem is fixed now?

**Comment by metincansiper** [comment]
@hasanbalci than you! It is working.
